import React, { useMemo } from 'react';
import { useAppStore } from '../store';
import { Copy } from 'lucide-react';

const ARDUINO_TEMPLATE_START = `// This is the code template for a 4x4x4 LED cube (common cathode)
// Generated by LED Cube Animator

#include <avr/pgmspace.h> // allows use of PROGMEM to store patterns in flash

#define CUBESIZE 4
#define PLANESIZE CUBESIZE*CUBESIZE
#define PLANETIME 100 // time each plane is displayed in us -> 100 Hz refresh
#define TIMECONST 20 // multiplies DisplayTime to get ms

const unsigned char PROGMEM PatternTable[] = {

  // this is a dummy element for start of table (duration=1) aka !!!DO NOT TOUCH!!!
  B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, 1,

  // --- BEGIN YOUR GENERATED ANIMATION ---
`;

const ARDUINO_TEMPLATE_END = `
  // --- END YOUR GENERATED ANIMATION ---

  // this is a dummy element for end of table (duration=0) aka !!!DO NOT TOUCH!!!
  B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, 0,
};

// Defining pins
int LEDPin[] = {6, A0, A3, 4, A1, 2, A5, A4, 13, 7, A2, 3, 8, 5, 1, 0};
int PlanePin[] = {12,11,9,10};

void setup() {
  int pin;
  for (pin = 0; pin < PLANESIZE; pin++) {
    pinMode( LEDPin[pin], OUTPUT );
  }
  for (pin = 0; pin < CUBESIZE; pin++) {
    pinMode( PlanePin[pin], OUTPUT );
  }
}

void loop() {
  byte PatternBuf[PLANESIZE];
  int PatternIdx = 0;
  byte DisplayTime;
  unsigned long EndTime;
  int plane, patbufidx, ledrow, ledcol, ledpin;

  do {
    memcpy_P( PatternBuf, PatternTable + PatternIdx, PLANESIZE );
    PatternIdx += PLANESIZE;
    DisplayTime = pgm_read_byte_near( PatternTable + PatternIdx++ );
    EndTime = millis() + ((unsigned long) DisplayTime) * TIMECONST;

    while ( millis() < EndTime ) {
      patbufidx = 0;
      for (plane = 0; plane < CUBESIZE; plane++) {
        if (plane == 0) {
          digitalWrite( PlanePin[CUBESIZE - 1], LOW );
        } else {
          digitalWrite( PlanePin[plane - 1], LOW );
        }

        ledpin = 0;
        for (ledrow = 0; ledrow < CUBESIZE; ledrow++) {
          for (ledcol = 0; ledcol < CUBESIZE; ledcol++) {
            digitalWrite( LEDPin[ledpin++], !(PatternBuf[patbufidx] & (1 << ledcol)) );
          }
          patbufidx++;
        }

        digitalWrite( PlanePin[plane], HIGH );
        delayMicroseconds( PLANETIME );
      }
    }
  } while (DisplayTime > 0);
}
`;

export function CodeExport() {
  const frames = useAppStore((state) => state.frames);

  const generatedCode = useMemo(() => {
    if (frames.length === 0) {
      return ARDUINO_TEMPLATE_START + "  // No keyframes added yet.\n" + ARDUINO_TEMPLATE_END;
    }

    const sorted = [...frames].sort((a, b) => a.time - b.time);
    const lines = [];

    for (let i = 0; i < sorted.length; i++) {
      const frame = sorted[i];
      const nextFrame = sorted[i + 1];
      
      let duration = nextFrame ? (nextFrame.time - frame.time) : 10;
      duration = Math.max(1, Math.min(255, duration));

      const bytes = [];
      for (let p = 0; p < 4; p++) {
        // We chunk by planes for readability in the code output
        const planeBytes = [];
        for (let r = 0; r < 4; r++) {
          let byteValue = 0;
          for (let c = 0; c < 4; c++) {
            const index = p * 16 + r * 4 + c;
            const isOff = !frame.leds[index];
            if (isOff) {
              byteValue |= (1 << c);
            }
          }
          planeBytes.push("B" + byteValue.toString(2).padStart(4, '0'));
        }
        bytes.push(planeBytes.join(','));
      }
      
      lines.push(`  ${bytes.join(', ')}, ${duration}, // Frame at time ${frame.time}`);
    }

    return ARDUINO_TEMPLATE_START + lines.join('\n') + ARDUINO_TEMPLATE_END;
  }, [frames]);

  return (
    <div className="flex flex-col h-full overflow-hidden bg-neutral-900 border border-neutral-800 rounded-lg">
      <div className="flex items-center justify-between p-4 bg-neutral-800 border-b border-neutral-700">
        <h2 className="text-lg font-medium text-white">Arduino Code Export</h2>
        <button
          onClick={() => {
            navigator.clipboard.writeText(generatedCode);
            alert('Copied to clipboard!');
          }}
          className="flex items-center space-x-2 px-3 py-1.5 bg-neutral-700 hover:bg-neutral-600 rounded text-sm text-white"
        >
          <Copy size={16} />
          <span>Copy code</span>
        </button>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <pre className="text-xs font-mono text-green-400 whitespace-pre">
          {generatedCode}
        </pre>
      </div>
    </div>
  );
}
