import React, { useMemo } from 'react';
import { useAppStore } from '../store';
import { Copy } from 'lucide-react';
import { LEDFrame } from '../types';
import { interpolateLeds } from '../lib/interpolation';

const ARDUINO_TEMPLATE_START = `// This is the code template for a 4x4x4 LED cube (common cathode)
// Generated by LED Cube Animator

#include <avr/pgmspace.h> // allows use of PROGMEM to store patterns in flash

#define CUBESIZE 4
#define PLANESIZE CUBESIZE*CUBESIZE
#define PLANETIME 100 // time each plane is displayed in us -> 100 Hz refresh
#define TIMECONST 20 // multiplies DisplayTime to get ms

const unsigned char PROGMEM PatternTable[] = {

  // this is a dummy element for start of table (duration=1) aka !!!DO NOT TOUCH!!!
  B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, 1,

  // --- BEGIN YOUR GENERATED ANIMATION ---
`;

const ARDUINO_TEMPLATE_END = `
  // --- END YOUR GENERATED ANIMATION ---

  // this is a dummy element for end of table (duration=0) aka !!!DO NOT TOUCH!!!
  B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, B1111, 0,
};

// Defining pins
int LEDPin[] = {6, A0, A3, 4, A1, 2, A5, A4, 13, 7, A2, 3, 8, 5, 1, 0};
int PlanePin[] = {12,11,9,10};

void setup() {
  int pin;
  for (pin = 0; pin < PLANESIZE; pin++) {
    pinMode( LEDPin[pin], OUTPUT );
  }
  for (pin = 0; pin < CUBESIZE; pin++) {
    pinMode( PlanePin[pin], OUTPUT );
  }
}
`;

function formatFrameData(frame: LEDFrame, duration: number): string {
  // Multiply by 5 to map app time unit (100ms) to Arduino TIMECONST (20ms).
  // E.g., duration 1 in app = 100ms = 5 in Arduino template
  // Make sure to round it to integer so it is valid C++ code.
  duration = Math.round(Math.max(1, Math.min(255, duration * 5)));
  const bytes = [];
  for (let p = 0; p < 4; p++) {
    const planeBytes = [];
    for (let r = 0; r < 4; r++) {
      let byteValue = 0;
      for (let c = 0; c < 4; c++) {
        const index = p * 16 + r * 4 + c;
        const isOff = !frame.leds[index];
        if (isOff) {
          byteValue |= (1 << c);
        }
      }
      planeBytes.push("B" + byteValue.toString(2).padStart(4, '0'));
    }
    bytes.push(planeBytes.join(','));
  }
  return `  ${bytes.join(', ')}, ${duration},`;
}

export function CodeExport() {
  const { frames, maxTime, loopMode, pingPong, repetitions, interpolate } = useAppStore();

  const generatedCode = useMemo(() => {
    let loopSetup = `\nvoid loop() {\n`;
    if (!loopMode) {
      loopSetup += `  static int repCount = 0;\n`;
      loopSetup += `  if (repCount >= ${repetitions}) {\n`;
      loopSetup += `    while(1) delay(1000); // Halt animation after repetitions\n`;
      loopSetup += `  }\n`;
      loopSetup += `  repCount++;\n\n`;
    }

    const arduinoLoopTemplateCodeBlock = `  byte PatternBuf[PLANESIZE];
  int PatternIdx = 0;
  byte DisplayTime;
  unsigned long EndTime;
  int plane, patbufidx, ledrow, ledcol, ledpin;

  do {
    memcpy_P( PatternBuf, PatternTable + PatternIdx, PLANESIZE );
    PatternIdx += PLANESIZE;
    DisplayTime = pgm_read_byte_near( PatternTable + PatternIdx++ );
    EndTime = millis() + ((unsigned long) DisplayTime) * TIMECONST;

    while ( millis() < EndTime ) {
      patbufidx = 0;
      for (plane = 0; plane < CUBESIZE; plane++) {
        if (plane == 0) {
          digitalWrite( PlanePin[CUBESIZE - 1], LOW );
        } else {
          digitalWrite( PlanePin[plane - 1], LOW );
        }

        ledpin = 0;
        for (ledrow = 0; ledrow < CUBESIZE; ledrow++) {
          for (ledcol = 0; ledcol < CUBESIZE; ledcol++) {
            digitalWrite( LEDPin[ledpin++], !(PatternBuf[patbufidx] & (1 << ledcol)) );
          }
          patbufidx++;
        }

        digitalWrite( PlanePin[plane], HIGH );
        delayMicroseconds( PLANETIME );
      }
    }
  } while (DisplayTime > 0);
}
`;
    
    if (frames.length === 0) {
      return ARDUINO_TEMPLATE_START + "  // No keyframes added yet.\n" + ARDUINO_TEMPLATE_END + loopSetup + arduinoLoopTemplateCodeBlock;
    }

    const sorted = [...frames].sort((a, b) => a.time - b.time);
    const sequence: { frame: LEDFrame, duration: number, comment: string }[] = [];

    // Forward pass
    const generateFrames = (f1: LEDFrame, f2: LEDFrame, duration: number, prefix: string) => {
      // duration is difference between times, so e.g. 5 means 5 time-ticks difference.
      if (interpolate && duration > 1 && f2) {
        for (let tick = 0; tick < duration; tick++) {
          const t = tick / duration;
          const interpLeds = interpolateLeds(f1.leds, f2.leds, t);
          sequence.push({
            frame: { id: '', time: f1.time + tick, leds: interpLeds },
            duration: 1, // each tick is length 1.
            comment: `${prefix} time ${f1.time + tick} (Interpolated)`
          });
        }
      } else {
        sequence.push({ frame: f1, duration, comment: `${prefix} time ${f1.time}` });
      }
    };

    for (let i = 0; i < sorted.length; i++) {
      const frame = sorted[i];
      const hasNext = (i + 1 < sorted.length);
      const nextFrame = hasNext ? sorted[i + 1] : frame; // nextFrame is fallback to same if no next
      const duration = hasNext ? (sorted[i + 1].time - frame.time) : Math.max(10, maxTime - frame.time);

      generateFrames(frame, nextFrame, duration, '// Frame at');
    }

    // Ping-Pong pass (Reverse)
    if (loopMode && pingPong && sorted.length > 1) {
      for (let i = sorted.length - 2; i >= 0; i--) {
        const frame = sorted[i + 1];
        const nextFrame = sorted[i];
        const duration = frame.time - nextFrame.time; // frame is later time, so frame - nextFrame is positive duration
        
        generateFrames(frame, nextFrame, duration, '// Reverse Frame to');
      }
    }

    const lines = sequence.map(s => formatFrameData(s.frame, s.duration) + ` ${s.comment}`);

    return ARDUINO_TEMPLATE_START + lines.join('\n') + ARDUINO_TEMPLATE_END + loopSetup + arduinoLoopTemplateCodeBlock;
  }, [frames, maxTime, loopMode, pingPong, repetitions, interpolate]);

  return (
    <div className="flex flex-col h-full overflow-hidden bg-neutral-900 border border-neutral-800 rounded-lg">
      <div className="flex items-center justify-between p-4 bg-neutral-800 border-b border-neutral-700">
        <h2 className="text-lg font-medium text-white">Arduino Code Export</h2>
        <button
          onClick={() => {
            navigator.clipboard.writeText(generatedCode);
            alert('Copied to clipboard!');
          }}
          className="flex items-center space-x-2 px-3 py-1.5 bg-neutral-700 hover:bg-neutral-600 rounded text-sm text-white"
        >
          <Copy size={16} />
          <span>Copy code</span>
        </button>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <pre className="text-xs font-mono text-green-400 whitespace-pre">
          {generatedCode}
        </pre>
      </div>
    </div>
  );
}
